- hosts: monitorhosts
  user: vega
  sudo: yes
  tasks:
    - name: copy bash shell and conf to host 
      copy: src={{ item }} dest=~ mode=0755
      with_items:
        - conf
        - telegraf.sh
        - telegraf.conf
        - .editorconfig
    - name: run shell
      command: bash /root/telegraf.sh
