version: '3'

services:
    #influx db service
    influxdb:
        image: influxdb:latest
        volumes:
            - ./data/influxdb:/var/lib/influxdb
        ports:
            - "8086:8086"
    telegraf:
        image: telegraf:latest
        volumes:
            - "./telegraf.conf:/etc/telegraf/telegraf.conf"
        depends_on:
            - influxdb
    kapacitor:
        image: kapacitor:latest
        ports:
            - "9092:9092"
        depends_on:
            - influxdb
        environment:
            KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    chronograf:
        image: chronograf:latest
        ports: 
            - "8888:8888"
        depends_on:
            - influxdb
