/* MASTER  */

GRANT REPLICATION SLAVE ON *.* TO 'slave_user'@'%' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;
USE newdatabase;
FLUSH TABLES WITH READ LOCK;
SHOW MASTER STATUS;


/* SALVE  */
CREATE DATABASE newdatabase;
CHANGE MASTER TO MASTER_HOST='192.168.158.48',MASTER_USER='root', MASTER_PASSWORD='password', MASTER_LOG_FILE='mysql-bin.000002', MASTER_LOG_POS=  589;
START SLAVE;
SHOW SLAVE STATUS\G
SET GLOBAL SQL_SLAVE_SKIP_COUNTER = 1; START SLAVE; 